# Generated by Django 5.2.7 on 2025-11-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estadop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='catalogos.estado')),
            ],
        ),
        migrations.CreateModel(
            name='colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('municipiop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonias', to='catalogos.municipio')),
            ],
        ),
    ]
