# Generated by Django 5.2.7 on 2025-12-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_municipio_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonia',
            name='codigo_p',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
