# Generated by Django 5.2.7 on 2025-12-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_colonia_codigo_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colonia',
            old_name='municipiop',
            new_name='municipio_p',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='codigo_p',
        ),
    ]
