# Generated by Django 5.2.7 on 2025-12-02 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_rename_municipiop_colonia_municipio_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonia',
            name='codigo_p',
            field=models.CharField(blank=True, help_text='Código postal (6 dígitos)', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='El código debe tener 6 dígitos', regex='^\\d{6}$')]),
        ),
    ]
