# Generated by Django 5.2.7 on 2025-12-02 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_colonia_codigo_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='codigo_p',
            field=models.CharField(blank=True, help_text='Código postal (5 dígitos)', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='El código debe tener 6 dígitos', regex='^\\d{5}$')]),
        ),
    ]
